# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Insite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Insite
  pod 'Mapbox-iOS-SDK', '~> 5.5'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'SnapKit'
  pod 'RIBs'
  pod 'RxSwift'
  pod 'RxGesture'
  pod 'RSLoadingView'
  pod 'PhoneNumberKit'
  pod 'M13Checkbox'
  pod 'MapboxNavigation', '~> 0.38'
  pod 'UberRides', '~> 0.12'
  pod 'RxDataSources'
  pod 'SwiftLocation'
  pod 'EFCountingLabel'
  pod 'LyftSDK'
end
